/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js normally; it is checked in here so the
// TypeScript project is valid before the first dev-server run.
